# version: "3.9"

services:
  backend-dev:
    build: 
      context: .
      dockerfile: backend_mern-authentication/Dockerfile.backend
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend_mern-authentication:/app
      - /app/node_modules
    env_file:
      - ./backend_mern-authentication/.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis

  frontend-dev:
    build: 
      context: .
      dockerfile: frontend_mern-authentication/Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend_mern-authentication:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - frontend_mern-authentication/.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - backend-dev

  backend-prod:
    build: 
      context: .
      dockerfile: backend_mern-authentication/Dockerfile.backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend_mern-authentication:/app
      - /app/node_modules
    env_file:
      - ./backend_mern-authentication/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis

  frontend-prod:
    build: 
      context: .
      dockerfile: frontend_mern-authentication/Dockerfile.frontend
      target: prod
    ports:
      - "5173:80"
    env_file:
      - frontend_mern-authentication/.env.dev
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-prod

  mongo:
    image: mongo:7.0
    container_name: mern-mongo
    ports:
      - "27017:27017"
    env_file:
      - ./backend_mern-authentication/.env.dev
    volumes:
      - mern-mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:8.6.1-alpine
    container_name: mern-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - mern-redis-data:/data
    restart: unless-stopped

volumes:
  mern-mongo-data:
  mern-redis-data: