version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mern-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mern-mongo-data:/data/db
    restart: unless-stopped

volumes:
  mern-mongo-data: